### ISSUE TITLE
Rename dec2 to dask-ec2

### ISSUE THREAD

**Issue by danielfrg** [conda-forge/dec2-feedstock#1]
We are in the process of renaming `dec2` to `dask-ec2` (https://github.com/dask/dask-ec2/pull/21) as a library and package in pypi and we would like to do the same for this `conda-forge` recipe. I don't know if this has happened in the past but I wanted to get opinions on the best way of doing this.

cc. @jakirkham

**Comment by pelson** [comment]
Hi @danielfrg. For the time being, simply renaming the package in the recipe will do the trick (I think). I have linked to an issue which should be the place to develop and document how to go about renaming a feedstock. I have done it once before manually, and honestly, I'd rather automate the thing 😉 

Does that work for you for the time being?

**Comment by jakirkham** [comment]
Well, there isn't really much history here. Could we just put the renamed package through staged-recipes? Or is there something else I'm missing here?

**Comment by danielfrg** [comment]
Yes, submitting again through `staged-recipes` was my first idea but wanted to get some feedback first. I kinda just wanted to not have a zombie `dec2-feedstock` repo when we are going to be updating the new `dask-ec2-feedstock`. If you guys are ok with that then I will submit a new one feedstock.

If we prefer to rename the repo can I get one of the admins to rename this repo to `dask-ec2-feedstock`? And I will update the recipe to match the new package.

**Comment by pelson** [comment]
Feel free to just update the package name in the recipe. The repo rename will have to be done once we have tooled appropriately - it will happen as there is a clear need for it.

Right now, I'd prefer taking this approach to the zombie repo approach of resubmitting to staged-recipes.

**Comment by CJ-Wright** [comment]
Would it be possible to put the outcome of this conversation where people could get at it more sally (an FAQ or manual?) This seems like an important thing to know (in case you miss-name a package) but takes some very artful googling to find.

**Comment by jakirkham** [comment]
Sure, that was at least one of the goals of issue ( https://github.com/conda-forge/conda-forge.github.io/issues/179 ). Would you be interested in doing a PR to docs repo, @CJ-Wright?

**Comment by CJ-Wright** [comment]
@jakirkham Is there anywhere in particular you would like this info in the docs?

**Comment by jakirkham** [comment]
Not sure ATM. Let's move this discussion over to webpage repo issue ( https://github.com/conda-forge/conda-forge.github.io/issues/179 ).
